version: '3'

volumes:
  postgres_data:

services:
  web:
    build: .
    command: ./entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:14.9
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
